"""Add gamification fields to users table

Revision ID: 4fb89c14d13c
Revises: c9ba5bdc8aa4
Create Date: 2026-03-10 21:41:54.966256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb89c14d13c'
down_revision: Union[str, None] = 'c9ba5bdc8aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products_stats_views', table_name='products')
    op.create_index('idx_products_stats_views', 'products', [sa.text("CAST(stats -> 'views' AS INTEGER) DESC")], unique=False)
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('max_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('freeze_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'freeze_count')
    op.drop_column('users', 'max_streak')
    op.drop_column('users', 'current_streak')
    op.drop_index('idx_products_stats_views', table_name='products')
    op.create_index('idx_products_stats_views', 'products', [sa.text("((stats -> 'views'::text)::integer) DESC")], unique=False)
    # ### end Alembic commands ###
