"""Initial tables

Revision ID: c9ba5bdc8aa4
Revises: 
Create Date: 2026-02-24 22:35:42.244738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9ba5bdc8aa4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('affiliate_tag', sa.String(length=100), nullable=True),
    sa.Column('selectors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scrape_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_platforms_active', 'platforms', ['is_active'], unique=False)
    op.create_index(op.f('ix_platforms_is_active'), 'platforms', ['is_active'], unique=False)
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_ai_tags', 'products', ['ai_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_products_brand', 'products', ['brand'], unique=False)
    op.create_index('idx_products_category', 'products', ['category'], unique=False)
    op.create_index('idx_products_fingerprint', 'products', ['fingerprint'], unique=False)
    op.create_index('idx_products_stats_views', 'products', [sa.text("CAST(stats -> 'views' AS INTEGER) DESC")], unique=False)
    op.create_index('idx_products_title_search', 'products', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_fingerprint'), 'products', ['fingerprint'], unique=True)
    op.create_table('streak_milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=30), nullable=False),
    sa.Column('reward_value', sa.Integer(), nullable=False),
    sa.Column('badge_emoji', sa.String(length=10), nullable=True),
    sa.Column('badge_name', sa.String(length=50), nullable=True),
    sa.Column('badge_color', sa.String(length=7), nullable=True),
    sa.Column('announcement_text', sa.String(length=200), nullable=True),
    sa.Column('confetti_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_streak_days', 'streak_milestones', ['streak_days'], unique=False)
    op.create_index(op.f('ix_streak_milestones_streak_days'), 'streak_milestones', ['streak_days'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('price_inr', sa.Float(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('badge_color', sa.String(length=7), nullable=True),
    sa.Column('badge_emoji', sa.String(length=10), nullable=True),
    sa.Column('tagline', sa.String(length=100), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('scraping_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analytics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_processing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('archived_to_git', sa.Boolean(), nullable=True),
    sa.Column('archive_path', sa.String(length=255), nullable=True),
    sa.Column('archive_size_mb', sa.Float(), nullable=True),
    sa.Column('github_commit_hash', sa.String(length=40), nullable=True),
    sa.Column('github_committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_logs_date', 'system_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_system_logs_log_date'), 'system_logs', ['log_date'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('hardware_id', sa.String(length=128), nullable=True),
    sa.Column('ip_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_platform', sa.String(length=20), nullable=True),
    sa.Column('usage_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('watchlist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alert_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('streak_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('referral_code', sa.String(length=8), nullable=True),
    sa.Column('referred_by', sa.String(length=8), nullable=True),
    sa.Column('referral_count', sa.Integer(), nullable=True),
    sa.Column('referral_rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("plan IN ('free', 'pro', 'premium')", name='check_valid_plan'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_active', 'users', ['is_blocked'], unique=False, postgresql_where=sa.text('is_blocked = false'))
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_firebase', 'users', ['firebase_uid'], unique=False)
    op.create_index('idx_users_last_login', 'users', ['last_login'], unique=False)
    op.create_index('idx_users_plan', 'users', ['plan'], unique=False)
    op.create_index('idx_users_referral_code', 'users', ['referral_code'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_hardware_id'), 'users', ['hardware_id'], unique=False)
    op.create_index(op.f('ix_users_is_blocked'), 'users', ['is_blocked'], unique=False)
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_plan'), 'users', ['plan'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_referred_by'), 'users', ['referred_by'], unique=False)
    op.create_table('product_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('affiliate_url', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('review_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('stock_count', sa.Integer(), nullable=True),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('last_scraped', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scrape_error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'external_id', name='uq_platform_external')
    )
    op.create_index('idx_listings_platform', 'product_listings', ['platform_id'], unique=False)
    op.create_index('idx_listings_price', 'product_listings', ['current_price'], unique=False)
    op.create_index('idx_listings_product', 'product_listings', ['product_id'], unique=False)
    op.create_index('idx_listings_scraped', 'product_listings', ['last_scraped'], unique=False)
    op.create_index('idx_listings_stock', 'product_listings', ['in_stock'], unique=False, postgresql_where=sa.text('in_stock = true'))
    op.create_index(op.f('ix_product_listings_current_price'), 'product_listings', ['current_price'], unique=False)
    op.create_index(op.f('ix_product_listings_in_stock'), 'product_listings', ['in_stock'], unique=False)
    op.create_index(op.f('ix_product_listings_last_scraped'), 'product_listings', ['last_scraped'], unique=False)
    op.create_index(op.f('ix_product_listings_platform_id'), 'product_listings', ['platform_id'], unique=False)
    op.create_index(op.f('ix_product_listings_product_id'), 'product_listings', ['product_id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('target_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_user_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_min_users', sa.Integer(), nullable=True),
    sa.Column('target_max_users', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(length=100), nullable=True),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_impressions', sa.Integer(), nullable=True),
    sa.Column('max_clicks', sa.Integer(), nullable=True),
    sa.Column('max_budget_inr', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pricing_model', sa.String(length=20), nullable=False),
    sa.Column('rate_inr', sa.Float(), nullable=False),
    sa.Column('pricing_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('brand_contact_email', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint("campaign_type IN ('featured_product', 'banner', 'sponsored_search', 'push_notification', 'takeover')", name='check_valid_campaign_type'),
    sa.CheckConstraint("payment_status IN ('pending', 'paid', 'refunded', 'cancelled')", name='check_valid_payment_status'),
    sa.CheckConstraint("pricing_model IN ('cpm', 'cpc', 'flat')", name='check_valid_pricing_model'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_promotions_active', 'promotions', ['is_active', 'start_date', 'end_date'], unique=False)
    op.create_index('idx_promotions_brand', 'promotions', ['brand_name'], unique=False)
    op.create_index('idx_promotions_dates', 'promotions', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_promotions_type', 'promotions', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_promotions_brand_name'), 'promotions', ['brand_name'], unique=False)
    op.create_index(op.f('ix_promotions_campaign_type'), 'promotions', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_promotions_is_active'), 'promotions', ['is_active'], unique=False)
    op.create_index(op.f('ix_promotions_payment_status'), 'promotions', ['payment_status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('purchase_token', sa.Text(), nullable=True),
    sa.Column('google_order_id', sa.String(length=100), nullable=True),
    sa.Column('acknowledgement_state', sa.String(length=20), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('commission_earned', sa.Float(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('listing_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_created', 'transactions', ['created_at'], unique=False)
    op.create_index('idx_transactions_google_order', 'transactions', ['google_order_id'], unique=False, postgresql_where=sa.text('google_order_id IS NOT NULL'))
    op.create_index('idx_transactions_platform', 'transactions', ['platform'], unique=False)
    op.create_index('idx_transactions_purchase_token', 'transactions', ['purchase_token'], unique=False, postgresql_where=sa.text('purchase_token IS NOT NULL'))
    op.create_index('idx_transactions_revenue', 'transactions', ['type', 'status'], unique=False, postgresql_where=sa.text("type IN ('payment', 'affiliate_conversion') AND status = 'success'"))
    op.create_index('idx_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('idx_transactions_type', 'transactions', ['type'], unique=False)
    op.create_index('idx_transactions_user', 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_google_order_id'), 'transactions', ['google_order_id'], unique=False)
    op.create_index(op.f('ix_transactions_platform'), 'transactions', ['platform'], unique=False)
    op.create_index(op.f('ix_transactions_razorpay_order_id'), 'transactions', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('user_watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product_watchlist')
    )
    op.create_index('ix_watchlist_user', 'user_watchlist', ['user_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_listing_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_listing_id'], ['product_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_history_listing_date', 'price_history', ['product_listing_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index('idx_price_history_listing_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('ix_watchlist_user', table_name='user_watchlist')
    op.drop_table('user_watchlist')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_razorpay_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_platform'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_google_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index('idx_transactions_user', table_name='transactions')
    op.drop_index('idx_transactions_type', table_name='transactions')
    op.drop_index('idx_transactions_status', table_name='transactions')
    op.drop_index('idx_transactions_revenue', table_name='transactions', postgresql_where=sa.text("type IN ('payment', 'affiliate_conversion') AND status = 'success'"))
    op.drop_index('idx_transactions_purchase_token', table_name='transactions', postgresql_where=sa.text('purchase_token IS NOT NULL'))
    op.drop_index('idx_transactions_platform', table_name='transactions')
    op.drop_index('idx_transactions_google_order', table_name='transactions', postgresql_where=sa.text('google_order_id IS NOT NULL'))
    op.drop_index('idx_transactions_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_promotions_payment_status'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_is_active'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_campaign_type'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_brand_name'), table_name='promotions')
    op.drop_index('idx_promotions_type', table_name='promotions')
    op.drop_index('idx_promotions_dates', table_name='promotions')
    op.drop_index('idx_promotions_brand', table_name='promotions')
    op.drop_index('idx_promotions_active', table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_product_listings_product_id'), table_name='product_listings')
    op.drop_index(op.f('ix_product_listings_platform_id'), table_name='product_listings')
    op.drop_index(op.f('ix_product_listings_last_scraped'), table_name='product_listings')
    op.drop_index(op.f('ix_product_listings_in_stock'), table_name='product_listings')
    op.drop_index(op.f('ix_product_listings_current_price'), table_name='product_listings')
    op.drop_index('idx_listings_stock', table_name='product_listings', postgresql_where=sa.text('in_stock = true'))
    op.drop_index('idx_listings_scraped', table_name='product_listings')
    op.drop_index('idx_listings_product', table_name='product_listings')
    op.drop_index('idx_listings_price', table_name='product_listings')
    op.drop_index('idx_listings_platform', table_name='product_listings')
    op.drop_table('product_listings')
    op.drop_index(op.f('ix_users_referred_by'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_plan'), table_name='users')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_index(op.f('ix_users_is_blocked'), table_name='users')
    op.drop_index(op.f('ix_users_hardware_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_referral_code', table_name='users')
    op.drop_index('idx_users_plan', table_name='users')
    op.drop_index('idx_users_last_login', table_name='users')
    op.drop_index('idx_users_firebase', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active', table_name='users', postgresql_where=sa.text('is_blocked = false'))
    op.drop_table('users')
    op.drop_index(op.f('ix_system_logs_log_date'), table_name='system_logs')
    op.drop_index('idx_system_logs_date', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_streak_milestones_streak_days'), table_name='streak_milestones')
    op.drop_index('idx_streak_days', table_name='streak_milestones')
    op.drop_table('streak_milestones')
    op.drop_index(op.f('ix_products_fingerprint'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index('idx_products_title_search', table_name='products', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_products_stats_views', table_name='products')
    op.drop_index('idx_products_fingerprint', table_name='products')
    op.drop_index('idx_products_category', table_name='products')
    op.drop_index('idx_products_brand', table_name='products')
    op.drop_index('idx_products_ai_tags', table_name='products', postgresql_using='gin')
    op.drop_table('products')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_is_active'), table_name='platforms')
    op.drop_index('idx_platforms_active', table_name='platforms')
    op.drop_table('platforms')
    op.drop_table('app_config')
    # ### end Alembic commands ###
